#!/bin/bash

die() {
  echo "$@" 1>&2
  exit 1
}

cd /projects/caldweba/

if [ ! -e balance.out ]; then
  die "balance.out was not generated by balance_queries.py"
fi

split_queries.sh
# This will take balance.out and split it into the individual files the node is responsible for in 
#  /projects/caldweba/perfqueries/

spawn_queries.sh &
# This will spawn N jobs in the background (where N is wc -l perfqueries/$HOSTNAME_perfqueries
#   and then wait until that sweep is complete. It writes the output to /projects/caldweba/logs/
#   It will loop forever until it is killed (by the slurm script)
